[package]
name = "bitvec"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.0"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
seq-macro = "0.3.5"
prettytable-rs = "0.10.0"
macro_const = "0.1.0"
memuse = "0.2.1"
colored = "2.1.0"
cfg-if = "1.0.0"
